// glyphcast homepage. The marketing site IS the moat argument: a hero Lottie
// (public/moat/ignite.json, generated by scripts/gen-moat-lottie.ts) plus four
// "door" Lotties, all played by lottie-web (light/SVG build). The four moat
// tiles and the proof strip run the REAL codec live (same encode/wire/renderer
// modules the lab and stations use) so the case is shown, not asserted, and a
// rotating ticker of real blind-LLM verdicts sits in the AI tile.
// Owns: lottie load, live GL renders, byte waterfall, ascii frame + copy-to-LLM,
// captured terminal frame, stat count-up, verdict ticker. NOT responsible for:
// codec internals (encode.ts/wire.ts/renderer_gl.ts) or the lab (main.ts).
// Test strategy: live browser - every Lottie renders nonblank, both GL canvases
// animate, bytes scroll real hex, verdicts type, no console errors.

// light build: SVG renderer only, no expression engine (drops the eval + ~half the bytes)
import lottie from 'lottie-web/build/player/lottie_light'
import { encodeCells, frameToPlainText, sampleX, sampleY } from './encode'
import { frameToColorText } from './llm-frame'
import { createRendererGL } from './renderer_gl'
import { createSampler } from './sampler'
import { createWireState, pack } from './wire'

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T
const video = $<HTMLVideoElement>('video')
const sampler = createSampler()
const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches

// ---------- hero Lottie ----------
const ignite = lottie.loadAnimation({
  container: $('ignite'),
  renderer: 'svg',
  loop: !reduce,
  autoplay: !reduce,
  path: '/moat/ignite.json',
})
if (reduce) ignite.addEventListener('DOMLoaded', () => ignite.goToAndStop(Math.round(ignite.totalFrames * 0.5), true))

// ---------- four door micro-Lotties (one per moat tile) ----------
for (const [id, path] of [['anim1', '/moat/door1.json'], ['anim2', '/moat/door2.json'], ['anim3', '/moat/door3.json'], ['anim4', '/moat/door4.json']] as const) {
  const el = document.getElementById(id)
  if (!el) continue
  const a = lottie.loadAnimation({ container: el, renderer: 'svg', loop: true, autoplay: !reduce, path })
  if (reduce) {
    a.addEventListener('DOMLoaded', () => a.goToAndStop(Math.round(a.totalFrames * 0.5), true))
    continue
  }
  // only animate while the tile is on screen
  new IntersectionObserver((es) => { for (const e of es) e.isIntersecting ? a.play() : a.pause() }, { threshold: 0.1 }).observe(el)
}

// ---------- two live GL glyph renders ----------
type Live = { canvas: HTMLCanvasElement; r: ReturnType<typeof createRendererGL>; cols: number; rows: number }
function makeLive(id: string): Live {
  return { canvas: $<HTMLCanvasElement>(id), r: createRendererGL($<HTMLCanvasElement>(id)), cols: 0, rows: 0 }
}
const proof = makeLive('proof-canvas')
const tv = makeLive('moat-tv')

function layoutLive(l: Live, px: number) {
  const rect = l.canvas.getBoundingClientRect()
  if (!rect.width) return
  l.r.resize(rect.width, rect.height)
  l.cols = Math.max(40, Math.min(140, Math.round(rect.width / px)))
  l.rows = Math.max(20, Math.round(l.cols * (rect.height / rect.width) * 0.5))
}
function layout() {
  layoutLive(proof, 7)
  layoutLive(tv, 6)
}
addEventListener('resize', layout)
video.addEventListener('loadedmetadata', layout)
layout()

function drawLive() {
  if (video.readyState >= 2) {
    if (proof.cols) proof.r.renderDirect(video, proof.cols, proof.rows, 'octant', 0, 0)
    if (tv.cols) tv.r.renderDirect(video, tv.cols, tv.rows, 'octant', 0, 0)
  }
  video.requestVideoFrameCallback(drawLive)
}
video.requestVideoFrameCallback(drawLive)

// ---------- byte waterfall (two mirrors of the real wire) ----------
const B_COLS = 22
const B_ROWS = 11
const fgBuf = new Uint8Array(B_COLS * B_ROWS * 4)
const bgBuf = new Uint8Array(B_COLS * B_ROWS * 4)
const sender = createWireState(B_COLS, B_ROWS)
const flows = ['byteflow', 'byteflow2'].map((id) => document.getElementById(id)).filter(Boolean) as HTMLElement[]
const byteLines: string[] = []

function pumpBytes() {
  if (video.readyState < 2) return
  const img = sampler.sample(video, B_COLS * sampleX('quadrant'), B_ROWS * sampleY('quadrant'))
  encodeCells(img, B_COLS, B_ROWS, 'quadrant', 0, fgBuf, bgBuf)
  const pkt = pack(sender, fgBuf, bgBuf, 'color', false).slice()
  const hex = [...pkt.slice(0, 14)].map((b) => b.toString(16).padStart(2, '0')).join(' ')
  byteLines.push(hex)
  if (byteLines.length > 26) byteLines.shift()
  const text = byteLines.join('\n')
  for (const f of flows) f.textContent = text
}
setInterval(pumpBytes, 200)

// ---------- ascii frame (moat tile 01) ----------
const asciframe = $('asciframe')
let aCols = 74
let aRows = 13
function sizeAscii() {
  const box = asciframe.parentElement!.getBoundingClientRect()
  aCols = Math.max(48, Math.min(140, Math.round(box.width / 4.3)))
  aRows = Math.max(10, Math.min(48, Math.round(box.height / 7.4)))
}
function pumpAscii() {
  if (video.readyState < 2) return
  const img = sampler.sample(video, aCols * sampleX('ascii'), aRows * sampleY('ascii'))
  asciframe.textContent = frameToPlainText(img, aCols, aRows)
}
sizeAscii()
addEventListener('resize', sizeAscii)
setInterval(pumpAscii, 220)

// ---------- copy a frame for your own LLM ----------
const copyllm = $<HTMLButtonElement>('copyllm')
copyllm.addEventListener('click', () => {
  if (video.readyState < 2) return
  // send the COLOUR frame (a palette legend + a letter grid of colour regions),
  // the same colour representation the 83% blind benchmark was measured on, so
  // the model reconstructs the scene from colours, not just brightness
  const C = 54
  const R = 26
  const img = sampler.sample(video, C * 3, R * 3)
  const frame = frameToColorText(img, C, R, 12)
  const prompt =
    'Below is one frame of a video, encoded as plain text - no pixels at all. First a colour ' +
    'palette (each letter maps to a hex colour and its name), then a grid where every letter is ' +
    "that colour's region in the frame. Reconstruct the scene in your head from the colours and " +
    'their layout, then answer:\n' +
    '1) In one sentence, what colours, shapes and setting do you see?\n' +
    '2) Which scene is it? (A) an outdoor woodland or grassy meadow  (B) a city street at night  ' +
    '(C) a plate of food on a table  (D) a sailboat on open water\n\n' + frame
  void navigator.clipboard.writeText(prompt).then(() => {
    const orig = copyllm.textContent
    copyllm.textContent = 'copied, paste into ChatGPT, Claude, anything'
    setTimeout(() => (copyllm.textContent = orig), 2600)
  })
})

// ---------- captured terminal frame (moat tile 02) ----------
void fetch('/term-frame.html')
  .then((r) => r.text())
  .then((frag) => { $('termframe').innerHTML = frag.replace(/class="termframe"/, '') })

// ---------- stat count-up ----------
const sAi = $('s-ai')
if (!reduce) {
  const start = performance.now()
  const step = (now: number) => {
    const t = Math.min(1, (now - start) / 1300)
    sAi.textContent = `${Math.round(83 * (1 - Math.pow(1 - t, 3)))}%`
    if (t < 1) requestAnimationFrame(step)
  }
  requestAnimationFrame(step)
}

// ---------- blind-LLM verdict ticker (real logged results) ----------
const vSaid = document.getElementById('vSaid')
const vWho = document.getElementById('vWho')
if (vSaid && vWho) {
  const VERDICTS = [
    { who: 'claude opus · blind · color frame', said: 'A large grey rabbit fills the center-left, rounded head and upright ear against tan-and-green grass.' },
    { who: 'gpt · blind · free tier', said: 'A large rabbit-like animal standing side-on above a grassy ground.' },
    { who: 'claude opus · blind · the hard one', said: 'Two grey-brown forms with a bright magenta patch between them, like a held butterfly.' },
    { who: 'devstral 24B · local · $0', said: 'Identified 5 of 6 frames blind: 83%, versus 25% chance.' },
  ]
  let vi = 0
  const streamVerdict = () => {
    const v = VERDICTS[vi]
    vWho.textContent = v.who
    vSaid.innerHTML = '<span class="cur">▍</span>'
    let i = 0
    const tick = () => {
      i++
      vSaid.innerHTML = '"' + v.said.slice(0, i) + '"' + (i < v.said.length ? '<span class="cur">▍</span>' : ' ✓')
      if (i < v.said.length) setTimeout(tick, 22)
      else setTimeout(() => { vi = (vi + 1) % VERDICTS.length; streamVerdict() }, 3600)
    }
    setTimeout(tick, 300)
  }
  streamVerdict()
}

// ---------- fill every tile from the first decoded frame ----------
function populate() {
  if (proof.cols) proof.r.renderDirect(video, proof.cols, proof.rows, 'octant', 0, 0)
  if (tv.cols) tv.r.renderDirect(video, tv.cols, tv.rows, 'octant', 0, 0)
  pumpBytes()
  pumpAscii()
}
video.addEventListener('loadeddata', () => { layout(); sizeAscii(); populate() })

// ---------- autoplay kick ----------
let tries = 0
const kick = setInterval(() => {
  if (!video.paused) return clearInterval(kick)
  if (++tries > 6) return clearInterval(kick)
  void video.play().catch(() => {})
}, 400)

// ---------- mobile nav menu ----------
const navWrap = document.querySelector('.nav-wrap')
const navToggle = document.getElementById('navToggle')
if (navWrap && navToggle) {
  const setOpen = (open: boolean) => {
    navWrap.classList.toggle('open', open)
    navToggle.setAttribute('aria-expanded', String(open))
  }
  navToggle.addEventListener('click', () => setOpen(!navWrap.classList.contains('open')))
  for (const a of navWrap.querySelectorAll('.nav-links a')) a.addEventListener('click', () => setOpen(false))
  addEventListener('keydown', (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false) })
}
